### ISSUE TITLE
mapproxy-util pyproj issue

### ISSUE THREAD

**Issue by t-hey** [kartoza/docker-mapproxy#19]
I am using the mapproxy container from https://hub.docker.com/r/kartoza/mapproxy
When using the `mapproxy-util` in the docker container I get a message 
`Found libproj >=5. Using this library without pyproj is deprecated and not fully supported. Please install pyproj >= 2.`
When using the mapproxy-util autoconfig --capabilities http://10.12.16.6:8600/geoserver/wms?request=getCapabilities, I get a lot of errors like the following.
```
mapproxy.script.conf.sources - WARNING - unable to initialize srs for EPSG:66326405: error initializing Proj(proj_def=None, init='epsg:66326405'): b'no arguments in initialization list

Traceback (most recent call last):
  File "/usr/local/bin/mapproxy-util", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/mapproxy/script/util.py", line 387, in main
    commands[command]['func'](args)
  File "/usr/local/lib/python3.7/site-packages/mapproxy/script/conf/app.py", line 185, in config_command
    write_header(f, options.capabilities)
  File "/usr/local/lib/python3.7/site-packages/mapproxy/script/conf/app.py", line 59, in write_header
    print('# MapProxy configuration automatically generated from:', file=f)
  File "/usr/local/lib/python3.7/codecs.py", line 378, in write
    self.stream.write(data)
TypeError: write() argument must be str, not bytes
```

I upgraded the pip to version 22.0.3 and install pyproj 3.2.1.
But the error message is still there.
The end goal is to use  `mapproxy-util` to produce a yaml configuration file for my GeoServer.
Pip list gives me this result
```
mapproxy@69a7ae91e8bb:/$ pip list
Package    Version
---------- ---------
certifi    2021.10.8
MapProxy   1.13.0
Pillow     8.1.0
pip        22.0.3
pyproj     3.2.1
PyYAML     5.4.1
setuptools 51.1.2
Shapely    1.7.1
uWSGI      2.0.19.1
wheel      0.36.2
```

Please advise.

**Comment by NyakudyaA** [comment]
> I am using the mapproxy container from https://hub.docker.com/r/kartoza/mapproxy When using the `mapproxy-util` in the docker container I get a message `Found libproj >=5. Using this library without pyproj is deprecated and not fully supported. Please install pyproj >= 2.` When using the mapproxy-util autoconfig --capabilities http://10.12.16.6:8600/geoserver/wms?request=getCapabilities, I get a lot of errors like the following.
> 
> ```
> mapproxy.script.conf.sources - WARNING - unable to initialize srs for EPSG:66326405: error initializing Proj(proj_def=None, init='epsg:66326405'): b'no arguments in initialization list
> 
> Traceback (most recent call last):
>   File "/usr/local/bin/mapproxy-util", line 8, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.7/site-packages/mapproxy/script/util.py", line 387, in main
>     commands[command]['func'](args)
>   File "/usr/local/lib/python3.7/site-packages/mapproxy/script/conf/app.py", line 185, in config_command
>     write_header(f, options.capabilities)
>   File "/usr/local/lib/python3.7/site-packages/mapproxy/script/conf/app.py", line 59, in write_header
>     print('# MapProxy configuration automatically generated from:', file=f)
>   File "/usr/local/lib/python3.7/codecs.py", line 378, in write
>     self.stream.write(data)
> TypeError: write() argument must be str, not bytes
> ```
> 
> I upgraded the pip to version 22.0.3 and install pyproj 3.2.1. But the error message is still there. The end goal is to use `mapproxy-util` to produce a yaml configuration file for my GeoServer. Pip list gives me this result
> 
> ```
> mapproxy@69a7ae91e8bb:/$ pip list
> Package    Version
> ---------- ---------
> certifi    2021.10.8
> MapProxy   1.13.0
> Pillow     8.1.0
> pip        22.0.3
> pyproj     3.2.1
> PyYAML     5.4.1
> setuptools 51.1.2
> Shapely    1.7.1
> uWSGI      2.0.19.1
> wheel      0.36.2
> ```
> 
> Please advise.
This should be fixed by https://github.com/kartoza/docker-mapproxy/pull/17. Please try to build the container locally and revert so that I can merge and publish the image

**Comment by t-hey** [comment]
@NyakudyaA thanks for the response. It took me a while to figure out I have to build the docker image from the https://github.com/kartoza/docker-mapproxy/tree/file_perm branch. It builds and seems to work. I could generate a mapproxy and seed configuration file, using mapproxy-util. Still got a large number of these warnings.
`[2022-02-15 11:14:41,651] mapproxy.script.conf.sources - WARNING - unable to initialize srs for EPSG:62586413: Invalid projection: epsg:62586413: (Internal Proj Error: proj_create: crs not found)` but maybe its is srs codes not part of libproj, I don't know. But the configuration files is build, with a number of srs's in it. 

Thanks for the help.

**Comment by NyakudyaA** [comment]
This proj issue is a separate and should be checked on stack exchange or proj repo
