### ISSUE TITLE
Request: Introduce docker image tags

### ISSUE THREAD

**Issue by tristndev** [kartoza/docker-mapproxy#44]
Hi all,
I am using your `kartoza/mapproxy:latest` image as base image in a Dockerfile in which I subsequently add our custom yaml configuration files for mapproxy. Our Dockerfile is then deployed into a Kubernetes cluster and used in production.

For this setup, it would be very advantageous to have also specific tags or versions that I could pin the base image to in order to enable reproducibility of our builds regardless of the current latest tag.

The current changes regarding the sample config directory actually broke our setup as the custom configuration files seem to be ignored at the moment and just the sample configuration is loaded by mapproxy.

Is there a way to dicuss your image release strategy and introduce a versioning for the docker image? Or can you think off a different way to help solve my issues?

**Comment by NyakudyaA** [comment]
Hi, thanks for commenting. I have opened #43 to fix the issue of building a specific tag. Currently we would like to do the following 

* Adjust GitHub workflows to enable building specific tags
* Enable a tagged version to correspond to a release for reproducibility 
* Add test for the image - we need to decide what gets tested 

*Note*. It is always not recommended to use the latest in production.
I will tag the release as 1.5.1 before the merge.

When you say your changes are not being picked do you mean it's overiding the configs files or not adding them

**Comment by tristndev** [comment]
@NyakudyaA, sounds great thanks!

---

> When you say your changes are not being picked do you mean it's overiding the configs files or not adding them

The Dockerfile still copies my configuration into the default configuration directory `/mapproxy` (environment variable `MAPPROXY_DATA_DIR`) but it seems that the sample configuration is created and loaded regardless in the directory `/opt/sample_configs` (environment variable `SAMPLE_CONFIG_DIR`).

My custom configuration files are copied into the image, but not used.

**Comment by NyakudyaA** [comment]
This is fixed by https://github.com/kartoza/docker-mapproxy/pull/70
