### ISSUE TITLE
Entrypoint does not allow running mapproxy-seed or mapproxy-util

### ISSUE THREAD

**Issue by Firefishy** [kartoza/docker-mapproxy#48]
The entrypoint script does not support running any other CMD eg: `mapproxy-seed` or `mapproxy-util`

The following example would be expected to run `mapproxy-util` but instead the container immediately exits because of [start.sh conditional](https://github.com/kartoza/docker-mapproxy/blob/0134cd65ede32a8912b61d8c363bea6cd1f80f7d/scripts/start.sh#L5) has no alternative.
```
docker run kartoza/mapproxy mapproxy-util
```

Workaround which does work as expected:
```
docker run --entrypoint '' kartoza/mapproxy mapproxy-util
```

**Comment by NyakudyaA** [comment]
Do you think adding a blank conditional would suffice or is there a better alternative?
