### ISSUE TITLE
No `env` variable to control cache size.

### ISSUE THREAD

**Issue by theoway** [kartoza/docker-mapproxy#53]
Thank you for creating this awesome docker image.

I have been wondering if there is any way to set a hard limit on cache size. Either when using `file` as cache or `s3`.

I couldn't find anything related to this in documentation page.

I wonder if the cache grows without bounds. Because this way, it'll crash our server. 
Or if it automatically remove tiles using some policy like MRU, LRU etc., is there any way to set max limit on cache size?

**Comment by NyakudyaA** [comment]
There is no such env because we expect the user to figure that out with seeding rules. You can use the optionhttps://mapproxy.org/docs/nightly/seed.html#remove-before

To cleanup older tiles. Another thing to also watch out is your os running out of inodes before the space runs out

**Comment by theoway** [comment]
@NyakudyaA Thank you! This is very insightful. I completely forgot about inodes. 

So what I understand is, I'll have to configure maybe a cron job that will run cleanup periodically.
Is there any other way to deal with it?,
