### ISSUE TITLE
 Issue with services from .yaml files not being available after container restart in Portainer CE 2.19.2

### ISSUE THREAD

**Issue by spechtx** [kartoza/docker-mapproxy#65]
### What is the bug or the crash?

Firstly, I'd like to express my appreciation for the docker-mapproxy; it's a fantastic tool, and I'm grateful for the effort put into it.

I'm encountering an issue with running the container in Portainer CE 2.19.2, where my services from the .yaml files in the multi_mapproxy directory are not available after restarting the container. I am loading the mapproxy directory with the .yaml files at system startup from an external SSHFS storage.

**Expected Behavior**
When I restart the container, I expect all the services from the .yaml files in the mapproxy directory to be available, including mapproxy.yaml and seed.yaml.

**Actual Behavior**
After system reboot or restarting the container, none of the services are available, and even mapproxy.yaml and seed.yaml are not shown.

**Workaround**
Currently, I am working around this issue by:

Going to Stacks -> mapproxy.

On Stack details i click on `Stop this stack`
-> The Stack is stopping
Then i click on `Start this stack`
-> After these steps, all services become available. They will not, when i simply restart the container.

It would be more convenient if they loaded automatically at system start.

### Steps to reproduce the issue

To replicate the issue I'm experiencing with docker-mapproxy in Portainer CE 2.19.2, please follow these steps:

1. **Initial Setup:**
- Set up the multi_mapproxy directory to load at system startup with SSHFS. The following command is used in /etc/fstab to mount the directory:
```
user@storage.example: /mnt/[external_storage_sshfs] fuse.sshfs x-systemd.automount,_netdev,port=22,IdentityFile=/root/.ssh/id_rsa_[external_storage_sshfs],allow_other,uid=1000,gid=1000 0 0
```
- Ensure that the mapproxy service is defined in a Portainer Stack.
2. **Reboot System or Restart Container**
- Either reboot the entire system or simply restart the mapproxy container in Portainer.
3. **Check for Services**
- After the system reboot or container restart, check for the availability of services defined in .yaml files within the multi_mapproxy directory.
4. **Observe the Issue**
- You'll notice that none of the services are available, and even the services from mapproxy.yaml and seed.yaml are not shown.
5. **Apply Workaround**
- Navigate to Stacks -> mapproxy in Portainer.
- Stop the stack by clicking on Stop this stack.
- Once the stack has stopped, start it again by clicking on Start this stack.
- After these steps, all services should become available

### Versions

MapProxy 1.16.0
Docker 24.0.7, build afdd53b
Portainer CE 2.19.2
host: Debian 6.1.55-1 x86_64

### Additional context

This is my docker-compose i am using in portainer

version: '3.8'

services:
  mapproxy:
    image: kartoza/mapproxy
    container_name: mapproxy
    environment:
     - PRODUCTION=True
     - PROCESSES=4
     - CHEAPER=1
     - THREADS=10
     - MAPPROXY_USER_ID=1000
     - MAPPROXY_GROUP_ID=1000
     - MULTI_MAPPROXY=True
     - ALLOW_LISTING=True
     - LOGGING=True
     - HTTP_PROXY:http://x.x.x.x:3128
     - HTTPS_PROXY=http://x.x.x.x:3128
    # not opened on host, since its routed via Nginx Proxy Manager (npm-network)
    # ports:
    #  - "8080:8080"
    volumes:
      - /mnt/[external_storage_sshfs]/multi_mapproxy:/multi_mapproxy     
    restart: always
    networks:
      - npm-network
      
networks:
  npm-network:
    external: true

**Comment by NyakudyaA** [comment]
Does the issue occur with a normal docker volume?, what are the logs when restarting the container. Does the restart delete your files or it overlays them obscuring them

**Comment by JeepartN** [comment]
I belive this is related to an issue i had, It worked on older branches but on newer branches it seems to not launch with multi_mapproxy enabled on any restart past the first. I think i fixed it by removing "rm /multi_mapproxy.py" from start.sh. 

I also had a problem where i couldnt have mapproxy be attatched to a shared folder when it is started, since it attempts to change some folder permissions which i belive causes it to never start. I dont fully understand why these permissions need to change so i just removed the part where start.sh runs the "chown" command and it seems to work.

**Comment by JeepartN** [comment]
> The chown is to ensure that the container runs as none root. Running containers as root is a security concern

This makes sense. Still I could not get a network drive to work without changing this behaviour

**Comment by NyakudyaA** [comment]
should be fixed in https://github.com/kartoza/docker-mapproxy/pull/70, https://github.com/kartoza/docker-mapproxy/blob/master/scripts/start.sh#L202-L205
